# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 02:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=30, unique=True)),
                ('descricao', models.TextField()),
                ('foto_b64', models.CharField(blank=True, max_length=200000)),
                ('validade', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('unidade_validade', models.CharField(choices=[('Anos', 'Anos'), ('Meses', 'Meses'), ('Dias', 'Dias')], default='Anos', max_length=10)),
                ('peso', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('unidade_peso', models.CharField(choices=[('gramas', 'gramas'), ('Kg', 'Kg')], default='gramas', max_length=10)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('codigo_revista', models.CharField(blank=True, max_length=20)),
                ('obs', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
