# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='validade',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_revista',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código da revista'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto_b64',
            field=models.CharField(blank=True, max_length=200000, verbose_name='Foto transformada em base64'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Peso em gramas ou Kg'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_peso',
            field=models.CharField(choices=[('gramas', 'gramas'), ('Kg', 'Kg')], default='gramas', max_length=10, verbose_name='Unidade de peso utilizada (gramas ou Kg)'),
        ),
    ]
