# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20171210_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='Nome da categoria', max_length=30, unique=True)),
                ('situacao', models.CharField(choices=[('1', 'Ativo'), ('2', 'Descontinuado')], default='1', help_text='Situaçao (ativo ou descontinuado)', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='Nome da classificação', max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Descontinuado')], default='1', help_text='Situaçao (ativo ou descontinuado)', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_revista',
            field=models.CharField(blank=True, help_text='Código da revista', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(help_text='Descrição do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto_b64',
            field=models.CharField(blank=True, help_text='Foto transformada em base64', max_length=200000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome do produto', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.TextField(blank=True, help_text='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.PositiveIntegerField(default=0, help_text='Peso em gramas ou Kg', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_peso',
            field=models.CharField(choices=[('1', 'gramas'), ('2', 'Kg')], default='1', help_text='Unidade de peso utilizada (gramas ou Kg)', max_length=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=None, help_text='Categoria conforme a linha', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao',
            field=models.ForeignKey(default=None, help_text='Classificação conforme o tipo de uso', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.Classificacao'),
        ),
    ]
